env:
  browser: true
extends:
  - plugin:vue/vue3-recommended
  - eslint:recommended
  - "@vue/typescript/recommended"
parser: vue-eslint-parser
parserOptions:
  parser: "@typescript-eslint/parser"
  sourceType: module
plugins:
  - vue
  - "@typescript-eslint"
rules: {}
