[package]
name = "wasm-kazuhe-github-io"
version = "0.1.0"
authors = ["Ohara Kazuhiro"]
description = "WebAssembly package for my website."
repository = "https://github.com/kazuhe/kazuhe.github.io"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.84"
